### PR TITLE
Error fetching sources

### PR DESCRIPTION
**Pull request by DavyA**
Pls add this commit, there is an error fetching sources

https://github.com/ScrewdAOSP/platform_manifest/commit/47daf26c00d062f4cbc154a855970c4f7035822e

### CODE REVIEW

**Comment by f100cleveland** [comment]
m-dtc branch was just a test branch from a couple months ago.  Can you use
m branch or is something missing in it?

**Comment by DavyA** [comment]
Ok, I'll use m, then add different GCC.

**Comment by f100cleveland** [comment]
What gcc are you using?

**Comment by DavyA** [comment]
I'll use DragonTC or UberTC

**Comment by f100cleveland** [comment]
M branch is tracking ubertc and the DTC, you can use Smitty branch instead
of master. It should play well with source. But hopefully we'll have that
issue fixed soon

**Pull request closed without merging**
